services:

  backend:
    build: ./backend
    ports:
      - "8081:8081"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: digimaturity
    ports:
      - "3307:3306"